### ISSUE TITLE
Proposal Review

### ISSUE THREAD

**Issue by sewinter** [mfliedner/tafelspitz#1]
Hi Moritz, 

I very much appreciate the level of detail you've incorporated into your design docs: it'll serve you well throughout the capstone process. 

1. I'd recommend that your MVP sub-bullets be more specific. Right now they all say: 
 a. Smooth, bug-free navigation
 b. Adequate seed data to demonstrate the site's features
 c. Adequate CSS styling

2. The New User and New Session Forms look a bit like a mobile app. I think they'd be good candidates for a modal. Along those lines, I'd recommend incorporating front-end auth. It's slightly more complex, but I think it's more impressive and makes your app truly single-page. 

3. This isn't a big issue, but I'd recommend more variation in the size/design of the big three horizontal components on your front page (Reservation-search, Restaurant-index, Favorites-list). 

4. Phase 2: Don't worry about too much seeding. That early on, you only need enough data for testing purposes. 

5. Be sure to allot enough time for implementing the Google Maps API: it can be a little tricky. 

6. I'd recommend styling as you go (rather than designating styling phases). Oftentimes styling refines your understanding of your site's functionality.

**Comment by mfliedner** [comment]
Thanks a lot, this is helpful.  As for the sizes in 3., I didn't have
enough time to measure out all the components on Opentable after discarding
the ones I don't want to implement, thus some of the wireframes are more
symbolic than to scale.  Yes, I encountered some of Google Map's
intricacies: I don't expect for this project more complexity than the Bench
BnB project (rather less, actually). And yes, I am concerned about the
amount of styling work this will involve; this has always been a very slow
process in the class projects.

Moritz
